### ISSUE TITLE
Friendbot url returns Bad Request

### ISSUE THREAD

**Issue by fapulito** [xdbfoundation/DigitalBits#21]
Hello,

I'm trying to do the setup tutorial and was able to install and link digitalbits-sdk and digitalbits-base to generate a keypair. However there is an error in the next part of the code that directs the friendbot request to [the friendbot url](https://frontier.testnet.digitalbits.io/friendbot)

The error was 
```
{
  "type": "https://digitalbits.org/frontier-errors/bad_request",
  "title": "Bad Request",
  "status": 400,
  "detail": "The request you sent was invalid in some way.",
  "extras": {
    "invalid_field": "addr",
    "reason": "strkey is 0 bytes long; minimum valid length is 5"
  }
}
```

So I think maybe there is a different url for friendbot?

**Comment by dievri** [comment]
Hello,  @fapulito 

Friendbot url is valid. Friendbot takes public key as a addr parameter in url.

    https://friendbot.testnet.digitalbits.io/?addr=<PublicKey>

For example, to fund account GCYWZSWXEOM4J3LVP5C2HGEIPGKS3EB4UJ3HUQCY7ACDL5EG6YDRIEF6 on a test network, request url should be like following

    https://friendbot.testnet.digitalbits.io/?addr=GCYWZSWXEOM4J3LVP5C2HGEIPGKS3EB4UJ3HUQCY7ACDL5EG6YDRIEF6

Please, note, this request could take few seconds to proceed.

Valid response would be like this:

    {
      "_links": {
        "self": {
          "href": "https://frontier.testnet.digitalbits.io/transactions/dd094af6cdc3348139fd7f43ee94da01478fbad5d205d5a7c85e3bcc53e76d07"
        },
        "account": {
          "href": "https://frontier.testnet.digitalbits.io/accounts/GD6AAAYC65V3F7PKP5CCUHEDKLHA2R5XMWMRIQTZSAKP6VAMYBMWUFZL"
        },
        "ledger": {
          "href": "https://frontier.testnet.digitalbits.io/ledgers/1605614"
        },
        "operations": {
          "href": "https://frontier.testnet.digitalbits.io/transactions/dd094af6cdc3348139fd7f43ee94da01478fbad5d205d5a7c85e3bcc53e76d07/operations{?cursor,limit,order}",
          "templated": true
        },
        "effects": {
          "href": "https://frontier.testnet.digitalbits.io/transactions/dd094af6cdc3348139fd7f43ee94da01478fbad5d205d5a7c85e3bcc53e76d07/effects{?cursor,limit,order}",
          "templated": true
        },
        "precedes": {
          "href": "https://frontier.testnet.digitalbits.io/transactions?order=asc\u0026cursor=6896059620003840"
        },
        "succeeds": {
          "href": "https://frontier.testnet.digitalbits.io/transactions?order=desc\u0026cursor=6896059620003840"
        },
        "transaction": {
          "href": "https://frontier.testnet.digitalbits.io/transactions/dd094af6cdc3348139fd7f43ee94da01478fbad5d205d5a7c85e3bcc53e76d07"
        }
      },
      "id": "dd094af6cdc3348139fd7f43ee94da01478fbad5d205d5a7c85e3bcc53e76d07",
      "paging_token": "6896059620003840",
      "successful": true,
      "hash": "dd094af6cdc3348139fd7f43ee94da01478fbad5d205d5a7c85e3bcc53e76d07",
      "ledger": 1605614,
      "created_at": "2021-07-29T10:47:19Z",
      "source_account": "GD6AAAYC65V3F7PKP5CCUHEDKLHA2R5XMWMRIQTZSAKP6VAMYBMWUFZL",
      "source_account_sequence": "5795474250399745",
      "fee_account": "GD6AAAYC65V3F7PKP5CCUHEDKLHA2R5XMWMRIQTZSAKP6VAMYBMWUFZL",
      "fee_charged": "300",
      "max_fee": "300",
      "operation_count": 1,
      "envelope_xdr": "AAAAAgAAAAD8AAMC92uy/ep/RCocg1LODUe3ZZkUQnmQFP9UDMBZagAAASwAFJb0AAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAALYlko2FbY34B5mNfTQSA84/EDC5PbwfQdvACSxCQbhFAAAAAAAAAACxbMrXI5nE7XV/RaOYiHmVLZA8onZ6QFj4BDX0hvYHFAAAABdIdugAAAAAAAAAAAIMwFlqAAAAQDQbCOUfKw7w3UgmAVfPW4r8PNP12Le5K5EgKHPY4K4um1MlK5NKwJmwRaHnyH3APcNJvnG/Iqt5Vd/bVWwcPw1CQbhFAAAAQMSoEqQEbIgs5L0t89PLXpwpQwbC9HRJGHLI3cOfzVdpot73RGB9kUnwsCF3NVf0InwrnaCrERUkTYetdvXE/QI=",
      "result_xdr": "AAAAAAAAASwAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA=",
      "result_meta_xdr": "AAAAAgAAAAIAAAADABh/7gAAAAAAAAAA/AADAvdrsv3qf0QqHINSzg1Ht2WZFEJ5kBT/VAzAWWoAAAAAPDNfVAAUlvQAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABABh/7gAAAAAAAAAA/AADAvdrsv3qf0QqHINSzg1Ht2WZFEJ5kBT/VAzAWWoAAAAAPDNfVAAUlvQAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAAAAwAAAAMAGGlMAAAAAAAAAAC2JZKNhW2N+AeZjX00EgPOPxAwuT28H0HbwAksQkG4RQLGd8bxQiEIAAAAAAAAAEYAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAGH/uAAAAAAAAAAC2JZKNhW2N+AeZjX00EgPOPxAwuT28H0HbwAksQkG4RQLGd6+oyzkIAAAAAAAAAEYAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAGH/uAAAAAAAAAACxbMrXI5nE7XV/RaOYiHmVLZA8onZ6QFj4BDX0hvYHFAAAABdIdugAABh/7gAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA=",
      "fee_meta_xdr": "AAAABAAAAAMAFJb0AAAAAAAAAAD8AAMC92uy/ep/RCocg1LODUe3ZZkUQnmQFP9UDMBZagAAAAA8M2CAABSW9AAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAGH/uAAAAAAAAAAD8AAMC92uy/ep/RCocg1LODUe3ZZkUQnmQFP9UDMBZagAAAAA8M19UABSW9AAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAMAGGlMAAAAAAAAAAC300+A8SGiACMZeKQTbc3s0U6aNTBLD14/5rrFIEl/hAAAAAAACaB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEAGH/uAAAAAAAAAAC300+A8SGiACMZeKQTbc3s0U6aNTBLD14/5rrFIEl/hAAAAAAACaGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA==",
      "memo_type": "none",
      "signatures": [
        "NBsI5R8rDvDdSCYBV89bivw80/XYt7krkSAoc9jgri6bUyUrk0rAmbBFoefIfcA9w0m+cb8iq3lV39tVbBw/DQ==",
        "xKgSpARsiCzkvS3z08tenClDBsL0dEkYcsjdw5/NV2mi3vdEYH2RSfCwIXc1V/QifCudoKsRFSRNh6129cT9Ag=="
      ],
      "valid_after": "1970-01-01T00:00:00Z"
    }

**Comment by fapulito** [comment]
Thank you @dievri - I was able to fund an account. I'm not great with javascript and am a little unclear how to access the keypair after it is generated using the variable. But I manually entered the public key and have a balance now. I think the url in the code block might need to be updated

`
  url: 'https://frontier.testnet.digitalbits.io/friendbot'
`

**Comment by dievri** [comment]
@fapulito 
`https://frontier.testnet.digitalbits.io/friendbot` redirects to the `https://friendbot.testnet.digitalbits.io`

Please, take a look at this sample code. It will create random keypair, store it in variable `pair` and than fund account for than key 
```js
DigitalBitsSdk = require("xdb-digitalbits-sdk")
var request = require('request');
var pair = DigitalBitsSdk.Keypair.random();

console.log(pair.secret());
console.log(pair.publicKey());


request.get({
  url: 'https://frontier.testnet.digitalbits.io/friendbot,
  qs: { addr: pair.publicKey() },
  json: true
}, function(error, response, body) {
  if (error || response.statusCode !== 200) {
    console.error('ERROR!', error || body);
  }
  else {
    console.log('SUCCESS! You have a new account :)\n', body);
  }
});
```
